#!/home/coke/perl5/perlbrew/perls/perl-5.16.1/bin/perl

use Modern::Perl;
use Text::CSV;

my @types = qw/niecza rakudo rakudo.jvm pugs/;
my %line;
my %pass;

my $csv = Text::CSV->new() ;

my $best = "";
my $max = 0;
foreach my $type (@types) {
    my $output = `grep total ${type}_summary.out`;
    $output =~ s/total/$type/;
    chomp $output;
    $csv->parse($output);
    @{$line{$type}} = $csv->fields();
    $pass{$type} = 0+(split(',', $output))[1];
    if ($pass{$type} > $max) {
        $best = $type;
        $max = $pass{$type};
    }
}

my $date=`date +'%m/%d/%Y'`;
chomp $date;
my $roast_version=`(cd roast && git rev-parse --short HEAD)`;
chomp $roast_version;
my $line = "# $date $roast_version ${best}++ ($max)";

foreach my $type (sort @types) {
    next if $type eq $best;

    my $per = 0; 
    if ($max != 0) {
        $per = int( $pass{$type}/$max *100*100)/100;
    }
    $line .= "; $type ($per%)"
}

say $line;
foreach my $type (sort @types) {
    my $impl = shift @{$line{$type}};
    $impl = '"' . $impl . '"';
    printf "%-8s,%6s,%6s,%6s,%6s,%6s,%6s\n", $impl, @{$line{$type}};
}
