#!/bin/sh
nice -20 ./bin/spec.sh
nice -20 ./bin/pugs.sh
nice -20 ./bin/niecza.sh
nice -20 ./bin/rakudo.moar.sh
nice -20 ./bin/rakudo.parrot.sh
nice -20 ./bin/rakudo.jvm.sh
TEMPFILE="TEMPFILE"
PASSFILE="perl6_pass_rates.csv"
OUTPUT=`./cull`
HEADER=`head -1 $PASSFILE`
echo "$HEADER" > $TEMPFILE
echo "$OUTPUT" >> $TEMPFILE
tail -$(wc -l $PASSFILE|awk '{print $1-1}') $PASSFILE >> $TEMPFILE
mv $TEMPFILE $PASSFILE
git commit -m "today (automated commit)" "$PASSFILE" niecza_summary.out rakudo.jvm_summary.out pugs_summary.out rakudo.parrot_summary.out rakudo.moar_summary.out
