#!/bin/sh

#$(date +'%Y_%m_%d')

    cd rakudo
    git rb;
    (cd t/spec && git rb)
    perl Configure.pl --gen-parrot
    make all
    perl t/spec/test_summary rakudo 2>&1 | 
              tee ../rakudo_summary.out
    echo "========================="
    echo "#"
    echo "#"
    echo "# done rakudo"
    echo "#"
    echo "#"
    echo "========================="

