#!/bin/sh

    cd niecza
    git pull --rebase;
    (cd t/spec && git pull --rebase)
    make all
    /home/coke/perl5/perlbrew/perls/perl-5.14.2/bin/perl t/spec/test_summary niecza 2>&1 | 
              tee ../niecza_summary.out
