#!/bin/sh

#$(date +'%Y_%m_%d')

    cd niecza
    git pull --rebase;
    (cd t/spec && git pull --rebase)
    make all
    perl t/spec/test_summary niecza 2>&1 | 
              tee ../niecza_summary.out
    echo "========================="
    echo "#"
    echo "#"
    echo "# done niecza"
    echo "#"
    echo "#"
    echo "========================="

