#!/bin/sh

#$(date +'%Y_%m_%d')

    cd Pugs.hs
    git rb;
    (cd t/spec && git rb)
    (cd Pugs && make)
    nice -20 perl t/spec/test_summary pugs 2>&1 | 
              tee ../pugs_summary.out
    echo "========================="
    echo "#"
    echo "#"
    echo "# done pugs"
    echo "#"
    echo "#"
    echo "========================="

