#!/bin/sh

#$(date +'%Y_%m_%d')

    cd Pugs.hs
    git pull --rebase;
    (cd t/spec && git pull --rebase)
    (cd Pugs && make)
    /home/coke/perl5/perlbrew/perls/perl-5.14.2/bin/perl t/spec/test_summary pugs 2>&1 | 
              tee ../pugs_summary.out
    echo "========================="
    echo "#"
    echo "#"
    echo "# done pugs"
    echo "#"
    echo "#"
    echo "========================="

